/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateCategoryMgt2Args } from "./CreateCategoryMgt2Args";
import { UpdateCategoryMgt2Args } from "./UpdateCategoryMgt2Args";
import { DeleteCategoryMgt2Args } from "./DeleteCategoryMgt2Args";
import { CategoryMgt2FindManyArgs } from "./CategoryMgt2FindManyArgs";
import { CategoryMgt2FindUniqueArgs } from "./CategoryMgt2FindUniqueArgs";
import { CategoryMgt2 } from "./CategoryMgt2";
import { CategoryMgt2Service } from "../categoryMgt2.service";

@graphql.Resolver(() => CategoryMgt2)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class CategoryMgt2ResolverBase {
  constructor(
    protected readonly service: CategoryMgt2Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CategoryMgt2",
    action: "read",
    possession: "any",
  })
  async _categoryMgt2sMeta(
    @graphql.Args() args: CategoryMgt2FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CategoryMgt2])
  @nestAccessControl.UseRoles({
    resource: "CategoryMgt2",
    action: "read",
    possession: "any",
  })
  async categoryMgt2s(
    @graphql.Args() args: CategoryMgt2FindManyArgs
  ): Promise<CategoryMgt2[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CategoryMgt2, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CategoryMgt2",
    action: "read",
    possession: "own",
  })
  async categoryMgt2(
    @graphql.Args() args: CategoryMgt2FindUniqueArgs
  ): Promise<CategoryMgt2 | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CategoryMgt2)
  @nestAccessControl.UseRoles({
    resource: "CategoryMgt2",
    action: "create",
    possession: "any",
  })
  async createCategoryMgt2(
    @graphql.Args() args: CreateCategoryMgt2Args
  ): Promise<CategoryMgt2> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CategoryMgt2)
  @nestAccessControl.UseRoles({
    resource: "CategoryMgt2",
    action: "update",
    possession: "any",
  })
  async updateCategoryMgt2(
    @graphql.Args() args: UpdateCategoryMgt2Args
  ): Promise<CategoryMgt2 | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CategoryMgt2)
  @nestAccessControl.UseRoles({
    resource: "CategoryMgt2",
    action: "delete",
    possession: "any",
  })
  async deleteCategoryMgt2(
    @graphql.Args() args: DeleteCategoryMgt2Args
  ): Promise<CategoryMgt2 | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
