/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  IsOptional,
  IsString,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { FeatureUpdateManyWithoutRequirementsInput } from "./FeatureUpdateManyWithoutRequirementsInput";
import { Type } from "class-transformer";
import { EnumRequirementStatus } from "./EnumRequirementStatus";
import { UserUpdateManyWithoutRequirementsInput } from "./UserUpdateManyWithoutRequirementsInput";
@InputType()
class RequirementUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  modelChanged?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reqDesc?: string | null;

  @ApiProperty({
    required: false,
    type: () => FeatureUpdateManyWithoutRequirementsInput,
  })
  @ValidateNested()
  @Type(() => FeatureUpdateManyWithoutRequirementsInput)
  @IsOptional()
  @Field(() => FeatureUpdateManyWithoutRequirementsInput, {
    nullable: true,
  })
  reqFeatureId?: FeatureUpdateManyWithoutRequirementsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reqId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reqModelname?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reqModelpath?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reqName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reqPrereq?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reqType?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumRequirementStatus,
  })
  @IsEnum(EnumRequirementStatus)
  @IsOptional()
  @Field(() => EnumRequirementStatus, {
    nullable: true,
  })
  status?: "Active" | "InActive" | null;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutRequirementsInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutRequirementsInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutRequirementsInput, {
    nullable: true,
  })
  userId?: UserUpdateManyWithoutRequirementsInput;
}
export { RequirementUpdateInput };
