/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountUpdateManyWithoutProjectsInput } from "./AccountUpdateManyWithoutProjectsInput";
import { ValidateNested, IsOptional, IsString, IsDate } from "class-validator";
import { Type } from "class-transformer";
import { FeatureUpdateManyWithoutProjectsInput } from "./FeatureUpdateManyWithoutProjectsInput";
import { UserUpdateManyWithoutProjectsInput } from "./UserUpdateManyWithoutProjectsInput";
@InputType()
class ProjectUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AccountUpdateManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => AccountUpdateManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => AccountUpdateManyWithoutProjectsInput, {
    nullable: true,
  })
  accountId?: AccountUpdateManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: () => FeatureUpdateManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => FeatureUpdateManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => FeatureUpdateManyWithoutProjectsInput, {
    nullable: true,
  })
  features?: FeatureUpdateManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  projectDesc?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  projectEndDate?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  projectId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  projectName?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  projectStDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutProjectsInput, {
    nullable: true,
  })
  userId?: UserUpdateManyWithoutProjectsInput;
}
export { ProjectUpdateInput };
