/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserCreateInput } from "./UserCreateInput";
import { UserWhereInput } from "./UserWhereInput";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserUpdateInput } from "./UserUpdateInput";
import { User } from "./User";
import { HmProtestAccountFindManyArgs } from "../../hmProtestAccount/base/HmProtestAccountFindManyArgs";
import { HmProtestAccount } from "../../hmProtestAccount/base/HmProtestAccount";
import { HmProtestAccountWhereUniqueInput } from "../../hmProtestAccount/base/HmProtestAccountWhereUniqueInput";
import { HmProtestProjectFindManyArgs } from "../../hmProtestProject/base/HmProtestProjectFindManyArgs";
import { HmProtestProject } from "../../hmProtestProject/base/HmProtestProject";
import { HmProtestProjectWhereUniqueInput } from "../../hmProtestProject/base/HmProtestProjectWhereUniqueInput";
import { HmProtestRequirementFindManyArgs } from "../../hmProtestRequirement/base/HmProtestRequirementFindManyArgs";
import { HmProtestRequirement } from "../../hmProtestRequirement/base/HmProtestRequirement";
import { HmProtestRequirementWhereUniqueInput } from "../../hmProtestRequirement/base/HmProtestRequirementWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserControllerBase {
  constructor(
    protected readonly service: UserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.create({
      data: {
        ...data,

        hmProtestAccountUser: data.hmProtestAccountUser
          ? {
              connect: data.hmProtestAccountUser,
            }
          : undefined,

        hmProtestFeature: data.hmProtestFeature
          ? {
              connect: data.hmProtestFeature,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        firstName: true,

        hmProtestAccountUser: {
          select: {
            id: true,
          },
        },

        hmProtestFeature: {
          select: {
            id: true,
          },
        },

        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        userDesc: true,
        userEndDate: true,
        username: true,
        userPlan: true,
        userStatus: true,
        userStDate: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(UserFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        firstName: true,

        hmProtestAccountUser: {
          select: {
            id: true,
          },
        },

        hmProtestFeature: {
          select: {
            id: true,
          },
        },

        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        userDesc: true,
        userEndDate: true,
        username: true,
        userPlan: true,
        userStatus: true,
        userStDate: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        firstName: true,

        hmProtestAccountUser: {
          select: {
            id: true,
          },
        },

        hmProtestFeature: {
          select: {
            id: true,
          },
        },

        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        userDesc: true,
        userEndDate: true,
        username: true,
        userPlan: true,
        userStatus: true,
        userStDate: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          hmProtestAccountUser: data.hmProtestAccountUser
            ? {
                connect: data.hmProtestAccountUser,
              }
            : undefined,

          hmProtestFeature: data.hmProtestFeature
            ? {
                connect: data.hmProtestFeature,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          firstName: true,

          hmProtestAccountUser: {
            select: {
              id: true,
            },
          },

          hmProtestFeature: {
            select: {
              id: true,
            },
          },

          id: true,
          lastName: true,
          roles: true,
          updatedAt: true,
          userDesc: true,
          userEndDate: true,
          username: true,
          userPlan: true,
          userStatus: true,
          userStDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          firstName: true,

          hmProtestAccountUser: {
            select: {
              id: true,
            },
          },

          hmProtestFeature: {
            select: {
              id: true,
            },
          },

          id: true,
          lastName: true,
          roles: true,
          updatedAt: true,
          userDesc: true,
          userEndDate: true,
          username: true,
          userPlan: true,
          userStatus: true,
          userStDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "HmProtestAccount",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/hmProtestAccounts")
  @ApiNestedQuery(HmProtestAccountFindManyArgs)
  async findManyHmProtestAccounts(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<HmProtestAccount[]> {
    const query = plainToClass(HmProtestAccountFindManyArgs, request.query);
    const results = await this.service.findHmProtestAccounts(params.id, {
      ...query,
      select: {
        accountBdm: true,
        accountDesc: true,
        accountDm: true,
        accountEndDate: true,
        accountId: true,
        accountName: true,
        accountPm: true,
        accountStatus: true,
        accountStDate: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/hmProtestAccounts")
  async connectHmProtestAccounts(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: HmProtestAccountWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hmProtestAccounts: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/hmProtestAccounts")
  async updateHmProtestAccounts(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: HmProtestAccountWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hmProtestAccounts: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/hmProtestAccounts")
  async disconnectHmProtestAccounts(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: HmProtestAccountWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hmProtestAccounts: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "HmProtestProject",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/hmProtestProjects")
  @ApiNestedQuery(HmProtestProjectFindManyArgs)
  async findManyHmProtestProjects(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<HmProtestProject[]> {
    const query = plainToClass(HmProtestProjectFindManyArgs, request.query);
    const results = await this.service.findHmProtestProjects(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        projectDesc: true,
        projectEndDate: true,
        projectId: true,
        projectName: true,
        projectStDate: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/hmProtestProjects")
  async connectHmProtestProjects(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: HmProtestProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hmProtestProjects: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/hmProtestProjects")
  async updateHmProtestProjects(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: HmProtestProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hmProtestProjects: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/hmProtestProjects")
  async disconnectHmProtestProjects(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: HmProtestProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hmProtestProjects: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "HmProtestRequirement",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/hmProtestRequirements")
  @ApiNestedQuery(HmProtestRequirementFindManyArgs)
  async findManyHmProtestRequirements(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<HmProtestRequirement[]> {
    const query = plainToClass(HmProtestRequirementFindManyArgs, request.query);
    const results = await this.service.findHmProtestRequirements(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        modelChanged: true,
        reqDesc: true,
        reqId: true,
        reqModelname: true,
        reqModelpath: true,
        reqName: true,
        reqPrereq: true,
        reqType: true,
        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/hmProtestRequirements")
  async connectHmProtestRequirements(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: HmProtestRequirementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hmProtestRequirements: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/hmProtestRequirements")
  async updateHmProtestRequirements(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: HmProtestRequirementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hmProtestRequirements: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/hmProtestRequirements")
  async disconnectHmProtestRequirements(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: HmProtestRequirementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hmProtestRequirements: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
