/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateHmProtestProjectArgs } from "./CreateHmProtestProjectArgs";
import { UpdateHmProtestProjectArgs } from "./UpdateHmProtestProjectArgs";
import { DeleteHmProtestProjectArgs } from "./DeleteHmProtestProjectArgs";
import { HmProtestProjectFindManyArgs } from "./HmProtestProjectFindManyArgs";
import { HmProtestProjectFindUniqueArgs } from "./HmProtestProjectFindUniqueArgs";
import { HmProtestProject } from "./HmProtestProject";
import { HmProtestAccountFindManyArgs } from "../../hmProtestAccount/base/HmProtestAccountFindManyArgs";
import { HmProtestAccount } from "../../hmProtestAccount/base/HmProtestAccount";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { HmProtestProjectService } from "../hmProtestProject.service";

@graphql.Resolver(() => HmProtestProject)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class HmProtestProjectResolverBase {
  constructor(
    protected readonly service: HmProtestProjectService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "HmProtestProject",
    action: "read",
    possession: "any",
  })
  async _hmProtestProjectsMeta(
    @graphql.Args() args: HmProtestProjectFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [HmProtestProject])
  @nestAccessControl.UseRoles({
    resource: "HmProtestProject",
    action: "read",
    possession: "any",
  })
  async hmProtestProjects(
    @graphql.Args() args: HmProtestProjectFindManyArgs
  ): Promise<HmProtestProject[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => HmProtestProject, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "HmProtestProject",
    action: "read",
    possession: "own",
  })
  async hmProtestProject(
    @graphql.Args() args: HmProtestProjectFindUniqueArgs
  ): Promise<HmProtestProject | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => HmProtestProject)
  @nestAccessControl.UseRoles({
    resource: "HmProtestProject",
    action: "create",
    possession: "any",
  })
  async createHmProtestProject(
    @graphql.Args() args: CreateHmProtestProjectArgs
  ): Promise<HmProtestProject> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => HmProtestProject)
  @nestAccessControl.UseRoles({
    resource: "HmProtestProject",
    action: "update",
    possession: "any",
  })
  async updateHmProtestProject(
    @graphql.Args() args: UpdateHmProtestProjectArgs
  ): Promise<HmProtestProject | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => HmProtestProject)
  @nestAccessControl.UseRoles({
    resource: "HmProtestProject",
    action: "delete",
    possession: "any",
  })
  async deleteHmProtestProject(
    @graphql.Args() args: DeleteHmProtestProjectArgs
  ): Promise<HmProtestProject | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [HmProtestAccount])
  @nestAccessControl.UseRoles({
    resource: "HmProtestAccount",
    action: "read",
    possession: "any",
  })
  async accountId(
    @graphql.Parent() parent: HmProtestProject,
    @graphql.Args() args: HmProtestAccountFindManyArgs
  ): Promise<HmProtestAccount[]> {
    const results = await this.service.findAccountId(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [User])
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async userId(
    @graphql.Parent() parent: HmProtestProject,
    @graphql.Args() args: UserFindManyArgs
  ): Promise<User[]> {
    const results = await this.service.findUserId(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
