/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateCategoryMgtArgs } from "./CreateCategoryMgtArgs";
import { UpdateCategoryMgtArgs } from "./UpdateCategoryMgtArgs";
import { DeleteCategoryMgtArgs } from "./DeleteCategoryMgtArgs";
import { CategoryMgtFindManyArgs } from "./CategoryMgtFindManyArgs";
import { CategoryMgtFindUniqueArgs } from "./CategoryMgtFindUniqueArgs";
import { CategoryMgt } from "./CategoryMgt";
import { CategoryMgtService } from "../categoryMgt.service";

@graphql.Resolver(() => CategoryMgt)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class CategoryMgtResolverBase {
  constructor(
    protected readonly service: CategoryMgtService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CategoryMgt",
    action: "read",
    possession: "any",
  })
  async _categoryMgtsMeta(
    @graphql.Args() args: CategoryMgtFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CategoryMgt])
  @nestAccessControl.UseRoles({
    resource: "CategoryMgt",
    action: "read",
    possession: "any",
  })
  async categoryMgts(
    @graphql.Args() args: CategoryMgtFindManyArgs
  ): Promise<CategoryMgt[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CategoryMgt, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CategoryMgt",
    action: "read",
    possession: "own",
  })
  async categoryMgt(
    @graphql.Args() args: CategoryMgtFindUniqueArgs
  ): Promise<CategoryMgt | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CategoryMgt)
  @nestAccessControl.UseRoles({
    resource: "CategoryMgt",
    action: "create",
    possession: "any",
  })
  async createCategoryMgt(
    @graphql.Args() args: CreateCategoryMgtArgs
  ): Promise<CategoryMgt> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CategoryMgt)
  @nestAccessControl.UseRoles({
    resource: "CategoryMgt",
    action: "update",
    possession: "any",
  })
  async updateCategoryMgt(
    @graphql.Args() args: UpdateCategoryMgtArgs
  ): Promise<CategoryMgt | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CategoryMgt)
  @nestAccessControl.UseRoles({
    resource: "CategoryMgt",
    action: "delete",
    possession: "any",
  })
  async deleteCategoryMgt(
    @graphql.Args() args: DeleteCategoryMgtArgs
  ): Promise<CategoryMgt | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
