/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateHmProtestAccountUserArgs } from "./CreateHmProtestAccountUserArgs";
import { UpdateHmProtestAccountUserArgs } from "./UpdateHmProtestAccountUserArgs";
import { DeleteHmProtestAccountUserArgs } from "./DeleteHmProtestAccountUserArgs";
import { HmProtestAccountUserFindManyArgs } from "./HmProtestAccountUserFindManyArgs";
import { HmProtestAccountUserFindUniqueArgs } from "./HmProtestAccountUserFindUniqueArgs";
import { HmProtestAccountUser } from "./HmProtestAccountUser";
import { HmProtestAccountFindManyArgs } from "../../hmProtestAccount/base/HmProtestAccountFindManyArgs";
import { HmProtestAccount } from "../../hmProtestAccount/base/HmProtestAccount";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { HmProtestAccountUserService } from "../hmProtestAccountUser.service";

@graphql.Resolver(() => HmProtestAccountUser)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class HmProtestAccountUserResolverBase {
  constructor(
    protected readonly service: HmProtestAccountUserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "HmProtestAccountUser",
    action: "read",
    possession: "any",
  })
  async _hmProtestAccountUsersMeta(
    @graphql.Args() args: HmProtestAccountUserFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [HmProtestAccountUser])
  @nestAccessControl.UseRoles({
    resource: "HmProtestAccountUser",
    action: "read",
    possession: "any",
  })
  async hmProtestAccountUsers(
    @graphql.Args() args: HmProtestAccountUserFindManyArgs
  ): Promise<HmProtestAccountUser[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => HmProtestAccountUser, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "HmProtestAccountUser",
    action: "read",
    possession: "own",
  })
  async hmProtestAccountUser(
    @graphql.Args() args: HmProtestAccountUserFindUniqueArgs
  ): Promise<HmProtestAccountUser | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => HmProtestAccountUser)
  @nestAccessControl.UseRoles({
    resource: "HmProtestAccountUser",
    action: "create",
    possession: "any",
  })
  async createHmProtestAccountUser(
    @graphql.Args() args: CreateHmProtestAccountUserArgs
  ): Promise<HmProtestAccountUser> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => HmProtestAccountUser)
  @nestAccessControl.UseRoles({
    resource: "HmProtestAccountUser",
    action: "update",
    possession: "any",
  })
  async updateHmProtestAccountUser(
    @graphql.Args() args: UpdateHmProtestAccountUserArgs
  ): Promise<HmProtestAccountUser | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => HmProtestAccountUser)
  @nestAccessControl.UseRoles({
    resource: "HmProtestAccountUser",
    action: "delete",
    possession: "any",
  })
  async deleteHmProtestAccountUser(
    @graphql.Args() args: DeleteHmProtestAccountUserArgs
  ): Promise<HmProtestAccountUser | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [HmProtestAccount])
  @nestAccessControl.UseRoles({
    resource: "HmProtestAccount",
    action: "read",
    possession: "any",
  })
  async accountId(
    @graphql.Parent() parent: HmProtestAccountUser,
    @graphql.Args() args: HmProtestAccountFindManyArgs
  ): Promise<HmProtestAccount[]> {
    const results = await this.service.findAccountId(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [User])
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async userId(
    @graphql.Parent() parent: HmProtestAccountUser,
    @graphql.Args() args: UserFindManyArgs
  ): Promise<User[]> {
    const results = await this.service.findUserId(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
