/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsDate,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumHmProtestAccountAccountStatus } from "./EnumHmProtestAccountAccountStatus";
import { HmProtestAccountUser } from "../../hmProtestAccountUser/base/HmProtestAccountUser";
import { HmProtestProject } from "../../hmProtestProject/base/HmProtestProject";
import { User } from "../../user/base/User";
@ObjectType()
class HmProtestAccount {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  accountBdm!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  accountDesc!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  accountDm!: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  accountEndDate!: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  accountId!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  accountName!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  accountPm!: string | null;

  @ApiProperty({
    required: false,
    enum: EnumHmProtestAccountAccountStatus,
  })
  @IsEnum(EnumHmProtestAccountAccountStatus)
  @IsOptional()
  @Field(() => EnumHmProtestAccountAccountStatus, {
    nullable: true,
  })
  accountStatus?: "Active" | "InActive" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  accountStDate!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [HmProtestAccountUser],
  })
  @ValidateNested()
  @Type(() => HmProtestAccountUser)
  @IsOptional()
  hmProtestAccountUsers?: Array<HmProtestAccountUser>;

  @ApiProperty({
    required: false,
    type: () => [HmProtestProject],
  })
  @ValidateNested()
  @Type(() => HmProtestProject)
  @IsOptional()
  hmProtestProjects?: Array<HmProtestProject>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [User],
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  userId?: Array<User>;
}
export { HmProtestAccount };
