/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { HmProtestAccountService } from "../hmProtestAccount.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HmProtestAccountCreateInput } from "./HmProtestAccountCreateInput";
import { HmProtestAccountWhereInput } from "./HmProtestAccountWhereInput";
import { HmProtestAccountWhereUniqueInput } from "./HmProtestAccountWhereUniqueInput";
import { HmProtestAccountFindManyArgs } from "./HmProtestAccountFindManyArgs";
import { HmProtestAccountUpdateInput } from "./HmProtestAccountUpdateInput";
import { HmProtestAccount } from "./HmProtestAccount";
import { HmProtestAccountUserFindManyArgs } from "../../hmProtestAccountUser/base/HmProtestAccountUserFindManyArgs";
import { HmProtestAccountUser } from "../../hmProtestAccountUser/base/HmProtestAccountUser";
import { HmProtestAccountUserWhereUniqueInput } from "../../hmProtestAccountUser/base/HmProtestAccountUserWhereUniqueInput";
import { HmProtestProjectFindManyArgs } from "../../hmProtestProject/base/HmProtestProjectFindManyArgs";
import { HmProtestProject } from "../../hmProtestProject/base/HmProtestProject";
import { HmProtestProjectWhereUniqueInput } from "../../hmProtestProject/base/HmProtestProjectWhereUniqueInput";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HmProtestAccountControllerBase {
  constructor(
    protected readonly service: HmProtestAccountService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "HmProtestAccount",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HmProtestAccount })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: HmProtestAccountCreateInput
  ): Promise<HmProtestAccount> {
    return await this.service.create({
      data: data,
      select: {
        accountBdm: true,
        accountDesc: true,
        accountDm: true,
        accountEndDate: true,
        accountId: true,
        accountName: true,
        accountPm: true,
        accountStatus: true,
        accountStDate: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "HmProtestAccount",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [HmProtestAccount] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(HmProtestAccountFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<HmProtestAccount[]> {
    const args = plainToClass(HmProtestAccountFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        accountBdm: true,
        accountDesc: true,
        accountDm: true,
        accountEndDate: true,
        accountId: true,
        accountName: true,
        accountPm: true,
        accountStatus: true,
        accountStDate: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "HmProtestAccount",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HmProtestAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: HmProtestAccountWhereUniqueInput
  ): Promise<HmProtestAccount | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        accountBdm: true,
        accountDesc: true,
        accountDm: true,
        accountEndDate: true,
        accountId: true,
        accountName: true,
        accountPm: true,
        accountStatus: true,
        accountStDate: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "HmProtestAccount",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HmProtestAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: HmProtestAccountWhereUniqueInput,
    @common.Body() data: HmProtestAccountUpdateInput
  ): Promise<HmProtestAccount | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          accountBdm: true,
          accountDesc: true,
          accountDm: true,
          accountEndDate: true,
          accountId: true,
          accountName: true,
          accountPm: true,
          accountStatus: true,
          accountStDate: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "HmProtestAccount",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HmProtestAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: HmProtestAccountWhereUniqueInput
  ): Promise<HmProtestAccount | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          accountBdm: true,
          accountDesc: true,
          accountDm: true,
          accountEndDate: true,
          accountId: true,
          accountName: true,
          accountPm: true,
          accountStatus: true,
          accountStDate: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "HmProtestAccountUser",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/hmProtestAccountUsers")
  @ApiNestedQuery(HmProtestAccountUserFindManyArgs)
  async findManyHmProtestAccountUsers(
    @common.Req() request: Request,
    @common.Param() params: HmProtestAccountWhereUniqueInput
  ): Promise<HmProtestAccountUser[]> {
    const query = plainToClass(HmProtestAccountUserFindManyArgs, request.query);
    const results = await this.service.findHmProtestAccountUsers(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
        userAccountRole: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "HmProtestAccount",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/hmProtestAccountUsers")
  async connectHmProtestAccountUsers(
    @common.Param() params: HmProtestAccountWhereUniqueInput,
    @common.Body() body: HmProtestAccountUserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hmProtestAccountUsers: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "HmProtestAccount",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/hmProtestAccountUsers")
  async updateHmProtestAccountUsers(
    @common.Param() params: HmProtestAccountWhereUniqueInput,
    @common.Body() body: HmProtestAccountUserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hmProtestAccountUsers: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "HmProtestAccount",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/hmProtestAccountUsers")
  async disconnectHmProtestAccountUsers(
    @common.Param() params: HmProtestAccountWhereUniqueInput,
    @common.Body() body: HmProtestAccountUserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hmProtestAccountUsers: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "HmProtestProject",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/hmProtestProjects")
  @ApiNestedQuery(HmProtestProjectFindManyArgs)
  async findManyHmProtestProjects(
    @common.Req() request: Request,
    @common.Param() params: HmProtestAccountWhereUniqueInput
  ): Promise<HmProtestProject[]> {
    const query = plainToClass(HmProtestProjectFindManyArgs, request.query);
    const results = await this.service.findHmProtestProjects(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        projectDesc: true,
        projectEndDate: true,
        projectId: true,
        projectName: true,
        projectStDate: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "HmProtestAccount",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/hmProtestProjects")
  async connectHmProtestProjects(
    @common.Param() params: HmProtestAccountWhereUniqueInput,
    @common.Body() body: HmProtestProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hmProtestProjects: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "HmProtestAccount",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/hmProtestProjects")
  async updateHmProtestProjects(
    @common.Param() params: HmProtestAccountWhereUniqueInput,
    @common.Body() body: HmProtestProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hmProtestProjects: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "HmProtestAccount",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/hmProtestProjects")
  async disconnectHmProtestProjects(
    @common.Param() params: HmProtestAccountWhereUniqueInput,
    @common.Body() body: HmProtestProjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hmProtestProjects: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/userId")
  @ApiNestedQuery(UserFindManyArgs)
  async findManyUserId(
    @common.Req() request: Request,
    @common.Param() params: HmProtestAccountWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findUserId(params.id, {
      ...query,
      select: {
        createdAt: true,
        firstName: true,

        hmProtestAccountUser: {
          select: {
            id: true,
          },
        },

        hmProtestFeature: {
          select: {
            id: true,
          },
        },

        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        userDesc: true,
        userEndDate: true,
        username: true,
        userPlan: true,
        userStatus: true,
        userStDate: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "HmProtestAccount",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/userId")
  async connectUserId(
    @common.Param() params: HmProtestAccountWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userId: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "HmProtestAccount",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/userId")
  async updateUserId(
    @common.Param() params: HmProtestAccountWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userId: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "HmProtestAccount",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/userId")
  async disconnectUserId(
    @common.Param() params: HmProtestAccountWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userId: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
