/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  IsOptional,
  IsString,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { HmProtestFeatureCreateNestedManyWithoutHmProtestRequirementsInput } from "./HmProtestFeatureCreateNestedManyWithoutHmProtestRequirementsInput";
import { Type } from "class-transformer";
import { EnumHmProtestRequirementStatus } from "./EnumHmProtestRequirementStatus";
import { UserCreateNestedManyWithoutHmProtestRequirementsInput } from "./UserCreateNestedManyWithoutHmProtestRequirementsInput";
@InputType()
class HmProtestRequirementCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  modelChanged?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reqDesc?: string | null;

  @ApiProperty({
    required: false,
    type: () =>
      HmProtestFeatureCreateNestedManyWithoutHmProtestRequirementsInput,
  })
  @ValidateNested()
  @Type(() => HmProtestFeatureCreateNestedManyWithoutHmProtestRequirementsInput)
  @IsOptional()
  @Field(
    () => HmProtestFeatureCreateNestedManyWithoutHmProtestRequirementsInput,
    {
      nullable: true,
    }
  )
  reqFeatureId?: HmProtestFeatureCreateNestedManyWithoutHmProtestRequirementsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reqId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reqModelname?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reqModelpath?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reqName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reqPrereq?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reqType?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumHmProtestRequirementStatus,
  })
  @IsEnum(EnumHmProtestRequirementStatus)
  @IsOptional()
  @Field(() => EnumHmProtestRequirementStatus, {
    nullable: true,
  })
  status?: "Active" | "InActive" | null;

  @ApiProperty({
    required: true,
    type: () => UserCreateNestedManyWithoutHmProtestRequirementsInput,
  })
  @ValidateNested()
  @Type(() => UserCreateNestedManyWithoutHmProtestRequirementsInput)
  @IsOptional()
  @Field(() => UserCreateNestedManyWithoutHmProtestRequirementsInput, {
    nullable: true,
  })
  userId?: UserCreateNestedManyWithoutHmProtestRequirementsInput;
}
export { HmProtestRequirementCreateInput };
